# -*- coding: utf-8 -*-
"""school gradebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4iOYsZqRVDvgI8CK1xmKJqy16zWf6M4
"""

# Magical School Grade Management System

# Dictionary to store student names and their grades (as lists)
grades = {}

print("🧙‍♂️ Welcome to the Magical School Grade Manager!")

while True:
    print("\nChoose an option:")
    print("1. Add a new student")
    print("2. Add/update grades for a student")
    print("3. View student grades")
    print("4. View class summary")
    print("5. Exit")

    choice = input("Enter your choice (1-5): ")

    if choice == "1":
        name = input("Enter the new student's name: ").title()
        if name in grades:
            print(f"⚠️ {name} is already in the system.")
        else:
            grades[name] = []
            print(f"✅ {name} has been added to the system.")

    elif choice == "2":
        name = input("Enter the student's name: ").title()
        if name not in grades:
            print(f"❌ {name} is not in the system. Please add them first.")
            continue

        try:
            grade = float(input(f"Enter the grade for {name}: "))
            if 0 <= grade <= 100:
                grades[name].append(grade)
                print(f"✅ Grade {grade} added for {name}.")
            else:
                print("❌ Please enter a grade between 0 and 100.")
        except ValueError:
            print("❌ Invalid input. Please enter a number.")

    elif choice == "3":
        name = input("Enter the student's name: ").title()
        if name not in grades:
            print(f"❌ {name} is not in the system.")
            continue

        student_grades = grades[name]
        if student_grades:
            average = sum(student_grades) / len(student_grades)
            print(f"Grades for {name}: {student_grades}")
            print(f"Average grade: {average:.2f}")
        else:
            print(f"{name} has no grades recorded yet.")

    elif choice == "4":
        if not grades:
            print("No students in the system yet.")
            continue

        total_sum = 0
        total_count = 0
        print("\n📋 Class Summary:")
        for student, student_grades in grades.items():
            if student_grades:
                avg = sum(student_grades) / len(student_grades)
                print(f"{student}: Grades: {student_grades}, Average: {avg:.2f}")
                total_sum += sum(student_grades)
                total_count += len(student_grades)
            else:
                print(f"{student}: No grades yet")

        if total_count > 0:
            class_avg = total_sum / total_count
            print(f"\nClass Average: {class_avg:.2f}")
        else:
            print("\nClass Average: N/A (no grades yet)")

    elif choice == "5":
        print("🪄 Exiting the Magical School Grade Manager. Goodbye!")
        break

    else:
        print("❌ Invalid choice. Please select 1-5.")